161225-144218-jrWetterstation-31-INFO-

Wetterstation gestartet

161225-144218-jrWetterstation-46-ERROR-Global exception handler: 
Traceback (most recent call last):
  File "jrWetterstation.py", line 39, in <module>
    ky052.save()
  File "/home/robert/jrWetterstation/sensors/KY052_Sensor.py", line 58, in save
    rrdtool.update(self.rrdFile,'N:%s:%s' %(self.actTemp,self.actPress))
error: opening 'db/jrWetter.rrd': No such file or directory

161225-144745-jrWetterstation-31-INFO-

Wetterstation gestartet

